config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD
      - id: samuel-dockerhub
        username_var: JPL_DOCKERUSER
        password_var: JPL_DOCKERPASS
      - id: incd_openstack
        variable: OPENSTACK_URL
      - id: ifca-auth.dat
        type: file
        variable: JENKINS_AUTH_FILE

sqa_criteria:
  SvcQC.Dep:
    repos:
      ec3:
        container: ec3client
        commands:
          - |
            #!/bin/bash
            echo "Check auth.dat file:"
            ls -al "${IM_AUTH_FILE}"
            printf "$(cat /etc/ec3/templates/ubuntu-ost.radl)" "${OPENSTACK_URL}" "${IM_IMAGE_ID}" "${OPENSTACK_URL}" "${IM_IMAGE_ID}" > ./ubuntu-ost.radl
            echo "Printing radl file"
            cat ./ubuntu-ost.radl
            echo
            cp ./ubuntu-ost.radl /etc/ec3/templates/ubuntu-ost.radl
          - ec3 launch jepl_im_cluster kubernetes ubuntu-ost -a "${IM_AUTH_FILE}" -u ${IM_SERVER} -y
          - ec3 show jepl_im_cluster -r
          - |
            #!/bin/bash
            echo y | ec3 destroy jepl_im_cluster --force

environment:
  IM_AUTH_FILE: "/im/auth.dat"
  #IM_IMAGE_ID: "a309f7ac-2198-4ecf-9fb9-ff68c2197143" # IFCA Image ID
  IM_IMAGE_ID: "4266a328-0c0e-4aa7-9087-b868882d39cb" # INCD Image ID
  IM_SERVER: "https://appsgrycap.i3m.upv.es:31443/im/"
  OPENSTACK_ID_PORT: "5000"
  JPL_DOCKERPUSH: "ec3client"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: "45"

# Timeout after no activity in logs for this configuration (not the absolute duration)
timeout: 1800