config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD
      - id: samuel-dockerhub
        username_var: JPL_DOCKERUSER
        password_var: JPL_DOCKERPASS
      - id: ifca_openstack
        variable: OPENSTACK_URL
      - id: ifca_openstack_id
        username_var: OPENSTACK_USER
        password_var: OPENSTACK_PASS
      - id: upv_im_id
        username_var: IM_USER
        password_var: IM_PASS

sqa_criteria:
  SvcQC.Dep:
    repos:
      ec3:
        container: ec3client
        commands:
          - |
            #!/bin/bash
            if [ -f ${IM_AUTH_FILE} ]; then
              printf "$(cat ${IM_AUTH_FILE})" "${IM_USER}" "${IM_PASS}" ifca "https://${OPENSTACK_URL}:${OPENSTACK_ID_PORT}" "${OPENSTACK_USER}" "${OPENSTACK_PASS}" "VO:eosc-synergy.eu" "0432c17d955e4c8d8ab7db0384536d4e" "IFCA" "3.x_password" > ${IM_AUTH_FILE}
            else
              ls -al /im/auth
              exit 1
            fi
            echo "Check auth.dat file:"
            ls -al "${IM_AUTH_FILE}"
            printf "$(cat /etc/ec3/templates/ubuntu-ost.radl)" "${OPENSTACK_URL}" "${IM_IMAGE_ID}" "${OPENSTACK_URL}" "${IM_IMAGE_ID}" > ./ubuntu-ost.radl
            echo "Printing radl file"
            cat ./ubuntu-ost.radl
            echo
            cp ./ubuntu-ost.radl /etc/ec3/templates/ubuntu-ost.radl
          - ec3 launch jepl_im_cluster kubernetes ubuntu-ost -a "${IM_AUTH_FILE}" -u ${IM_SERVER} -y
          - ec3 show jepl_im_cluster -r
          - |
            #!/bin/bash
            ec3 destroy jepl_im_cluster --force -y

environment:
  IM_AUTH_FILE: "/im/auth/auth.dat"
  IM_IMAGE_ID: "a309f7ac-2198-4ecf-9fb9-ff68c2197143" # IFCA Image ID
  #IM_IMAGE_ID: "4266a328-0c0e-4aa7-9087-b868882d39cb" # INCD Image ID
  IM_SERVER: "https://appsgrycap.i3m.upv.es:31443/im/"
  OPENSTACK_ID_PORT: "5000"
  JPL_DOCKERPUSH: "ec3client"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: "45"

# Timeout after no activity in logs for this configuration (not the absolute duration)
timeout: 1800